### ISSUE TITLE
Mex disabled in `sort_pix`

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#1018]
Following issues with SegFaults in merging of #994 due to restructure of `sort_pix` mex is failing. As such mex will be disabled until fixed.

C.f. `horace_core/utilities/sort_pix`: 68 && `_LowLevelCode/cpp/sort_pixels_by_bins/sort_pixels_by_bins.{h,cpp}`

Consider refactor of `_LowLevelCode/cpp/sort_pixels_by_bins/sort_pixels_by_bins.{h,cpp}` to fix MEX for sort_pix by replacing reinterpret_cast & case with function signature dispatch

**Comment by abuts** [comment]
Addressed by #1589. We do not deed to sort pixels on file as this is part of generic memory based algorithm, which sorts pixels by bins and it may be partial bins

**Comment by abuts** [comment]
fixed and merged
