### ISSUE TITLE
Current implementation of combine_sqw is wrong

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1032]
`combine_sqw` and `join` are the old methods, which its original implementation beeing complex but valid. 
Somewhere during the development process, it has been reimplemented using PixelData.cat() operation, which does not maintains the order of pixels according to bins 
For `combine_sqw` it become very inefficient.
For `join` its wrong

Current implementation does not work with filebacked pixels unless they fit memory, does not check if all projections in the contributing files are complient and needs improvement

**Comment by cmarooney-stfc** [comment]
CLOSED against #886
