### ISSUE TITLE
fractional comparison is broken

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1033]
see test_pixels_equal-> test_using_fraction_argument_only_tests_fraction_of_the_bins

fails and debugging shows that fractions is not attempted.  

The test have been recovered merging master in #892. Its certainly not duplicated

**Comment by oerc0122** [comment]
Compare `_test/test_sqw_class/test_equal_to_tol` and `test_pixels_equal`, relevant different different tests were merged across before removing the duplicates.

**Comment by abuts** [comment]
following our conversation ,I need to add more. 
The previous comparison was comparting both pixels and distribution of pixels over bins. The second one is even more important as pixels in a bin can be distributed randomly, but it should be the same pixels. 
comparing just pixels does not make sense.

**Comment by oerc0122** [comment]
That is handled by reorder which sorts pixels according to their inner indices. I explicitly disable it in the new test as otherwise the zeroed bins get pushed to the top of the list and the comparison fails
