### ISSUE TITLE
Runmap_id performance and code consistency issues

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1135]
The piece of code located in Tobyfit-> tobyfit_DGdist_reconv_init, rows 233-236 is extreamly slow:
```
irun_max = max(irun);
    if irun_max>numel(ne)
        irun = arrayfun(@(x)wtmp.runid_map(x),irun);
    end
```
Apparently, this code calls modified `Experinent.runid_map` function which rebuilds runid_map on each call to this method. 
The call should be taken out of `arrayfun` on row 235. 

If it is still slow, the performance improvement methodology deployed in 
sqw->tobyfit_DGdisk_resconv ros 201-2014 should be deployed. It is a hack, so such code should probably be placed within `Experiment` and exposed in all places through something like `convert_runid_to_header_indexes`

CM: 18/9/23: See Toby comment at 3rd Sept on futher ramifications of this.
Is this performance improvement sufficient to drop the MVP label?

**Comment by tgperring** [comment]
This is a very serious inefficiency that should be solved for MVP. Profiling a  representative fit example from the PACE test suite (runtests test_tobyfit_cuts:test_fit_fe_rb_multi) showed that 50% of the entire run time (41.6 sec out of 80.7 sec on my laptop) was spent in the initialisation stage of the fit, at line 230 in tobyfit_DGfermi_resconv_init in the line:
       [irun,idet,ien] = parse_pixel_indices(wtmp); 
and in turn line 82 of parse_pixel_indices:
       irun_tmp = arrayfun(@(x) win(i).runid_map(x),run_idx);
was responsible for all but a fraction of  a second of that time.

That is: more time was spend just indexing pixels during the initialisation that in the entirely of the fit itself!

**Comment by abuts** [comment]
I beleive, the simple solution which would give at least 10-fold acceleration is 
```
    irun_max = max(irun);
    id_max = wtmp.runid_map;
    if irun_max>numel(ne)
        irun = arrayfun(@(x)id_max(x),irun);
    end
```
Similar issue should be present in DG_fermi

**Comment by cmarooney-stfc** [comment]
Adding that while @abuts comment at Aug 9 should be correct, in fact the equivalent DGfermi code does not recalculate irun from the runid_map, there is no equivalent arrayfun there, so I have not modified it. If it needed to add that code then it can be ticketed as a separate exercise.

**Comment by tgperring** [comment]
The major problem is in parse_pixel_indices. I've now changed that code, speeding up the call by an order of magnitude, but in my example code it is still taking 5% of the total time of the fit simply to perform the function of what is ultimately just indexing into an array! It is still the case that a solution along Alex's suggestion ("...be placed within Experiment and exposed in all places through something like convert_runid_to_header_indexes...") as this is a generic problem, it ought to be extremely fast, and Alex has pointed out that the 'hack' in tobyfit_DGdisk_resconv_init and tobyfit_DGfermi_resconv_init is not general, and is repeated code.

Chris' point about the code that appears on lines 238-242  in tobyfit_DGdisk_resconv_init but not in tobyfit_DGfermi_resconv_init is closely connected, so I leave it here as part of the same issue.

**Comment by cmarooney-stfc** [comment]
MVP removed to reflect the progress of this ticket. SHould now be closed and others migrated to new ticket
