### ISSUE TITLE
Make object_lookup serializable

### ISSUE THREAD

**Issue by tgperring** [pace-neutrons/Horace#1146]
object_lookup needs to be converted to serializable. It is coupled to the Herbert utility methods that sort objects. The opportunity will be used to clear out the remnants of the obsolete I/O save and load protocol previously used by instrument classes (e.g. loadobj_private). object_lookup is the last class that uses this old scheme.

**Comment by tgperring** [comment]
As part of these changes, the object_lookup tests as associated tests on classes created for those tests (boxClass and boxArrayClass) will be renamed so that the test functions themselves are more descriptive of what the tests are doing.

**Comment by cmarooney-stfc** [comment]
@cmarooney-stfc close this when PR number is available

**Comment by cmarooney-stfc** [comment]
@tgperring Toby, have you done this?

**Comment by tgperring** [comment]
This task was completed in PR #1169
