### ISSUE TITLE
Serializable equality method (eq) should be replaced by overloaded equal_to_tol

### ISSUE THREAD

**Issue by tgperring** [pace-neutrons/Horace#1147]
Should be part of common equal_to_tol refactoring for `PixelData`
also includes  is_cut_equal

Serializable has a method to check for equality, eq.m, that enables comparisons overloading == so that A==B is possible. However, by default it permits a tolerance of 1e-9 (relative and absolute) on numerical data. This has the potential to result in unexpected behaviour.

In fact, the use of eq.m for serializable objects at the moment appears only to be in tests, and the function has multiple optional input arguments and output to control tolerance, and return an error message, in contrast to the Matlab intrinsic function. Accordingly, eq.m is really just performing the function of an overloaded version of equal_to_tol. This should replace the current eq.m, and if it is desirable to overload the operators eq, ne etc they should have the precise correspondence with the Matlab intrinsic operation e.g. eq.m shoudl test true equality.

**Comment by abuts** [comment]
Addressed by PR #1793. 
`eq_to_tol` overloads made consistent with the structure of Horace objects including PixelDataBase.
Made it easy to overload `eq_to_tol` to any other object.
