### ISSUE TITLE
Prototype for apply paging operations

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1178]
This ticket is to implement prototype of the paging operations and apply method. See PR #1297 which implements it.

**Comment by cmarooney-stfc** [comment]
@abuts Hi Alex, just discussed this with Jacob; we need more detail on what is still disabled or invalid; Jacob thinks at least some of it is working

**Comment by cmarooney-stfc** [comment]
fixing along with #1091 joint fix
