### ISSUE TITLE
`change_crystal` does not respect deprecation

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#1213]
`change_crystal` will error out if provided old-style correction rather than issuing warning and continuing.

**Comment by cmarooney-stfc** [comment]
@oerc0122 Hi Jacob, can you add more detail here to enable someone to know where the failure is happening, what test it is in, what input needs to be provided - thanks

**Comment by oerc0122** [comment]
This is not about tests, this is about user usage. 

The failure is in `change_crystal` and the deprecated state is highlighted by an explicit `if then error` rather than trying to coerce the parameters into a valid form if possible. It may not be, hence the vagueness of the issue.

**Comment by oerc0122** [comment]
Determined to be difficult to maintain and fix.
