### ISSUE TITLE
Define performance tests

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#123]
The system test plan notes that a set of full performance tests should be defined.

This ticket will define what those test are:

- what data (small and large data sets)
- what processes
- which systems to run on

Output:

- detailed description of the test cases and test data
- where the test data can be obtained

**Comment by nickbattam-tessella** [comment]
Part of #46

**Comment by oerc0122** [comment]
Implemented as part of Olivier's benchmarking project
