### ISSUE TITLE
Create large test data management plan

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#141]
#122 is currently blocked as we do not have a good way of storing large data files for system tests.

An idea is to use GitLFS to pull the data files.

**Outputs:**
An ADR documenting where we'll store large data files and how they will be downloaded for system tests

**Comment by nickbattam-tessella** [comment]
Blocked waiting on response from SAN file system team

**Comment by nickbattam-tessella** [comment]
SAN storage area created with r/o access to all users (including build agents) and r/w access for named users.
