### ISSUE TITLE
Re-enable disabled job_dispatcher tests

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#143]
## This is a Herbert issue: https://github.com/pace-neutrons/Herbert/issues/92

- `test_job_dispatcher::test_job_with_logs_3workers` https://github.com/pace-neutrons/Herbert/commit/a2c3e2140179c97342a6d9160bd9697b7ab3a677
- `test_job_dispatcher::test_job_fail_restart` https://github.com/pace-neutrons/Herbert/commit/8543b3a32d24308a5e3c144fb59426a2eb0b772c

The tests disabled require 3 workers, but ANVIL's sl7 machines only offer us two cores. I've contacted them to try to resolve this. There may be some Matlab parallel toolbox configuration we can set to get the tests working, as it only seems to be the `parpool` versions of the tests that fail. 

I've been informed that the sl7 machines should have 2 physicals cores, with hyper-threading. So they should make 4 workers available to Matlab.

```
===== Test Case Failure =====
Location: 
Name:     test_job_dispatcher_parpool::test_job_with_logs_3workers

job test_parpool_3workers_YNNFMPQJJY requested 3 workers while the cluster allows only 2

===== Test Case Failure =====
Location: 
Name:     test_job_dispatcher_parpool::test_job_fail_restart

job test_job_parpool_fail_restart_OGPRFCHHKM requested 3 workers while the cluster allows only 2

```

**Comment by abuts** [comment]
I believe, this one has been fixed
