### ISSUE TITLE
Remove INSTALL_GTEST option from CMake

### ISSUE THREAD

**Issue by ghost** [pace-neutrons/Horace#149]
https://github.com/pace-neutrons/Herbert/issues/97

> In f1fdba6 the INSTALL_GTEST option was set to OFF - this stops GoogleTest libraries from being packaged into Herbert (it disables the install commands within GoogleTests's CMake). However, this created an INSTALL_GTEST option in the CMake GUI, since we never want to install GTest, this option should always be off and should therefore be removed/hidden.

**Comment by oerc0122** [comment]
Want to keep
