### ISSUE TITLE
Subtracting `dnd` from `sqw` results in `sqw`

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#1525]
Subtracting a `dnd` from an `sqw` results in an `sqw` object despite the pixels no longer mapping to the stored `dnd` and thus an invalid object. Should subsequent operations recompute the bins this will "undo" the subtraction.

Actually, the user complan was about documentation

**Comment by abuts** [comment]
That's interesting. I believe I've sorted this thing properly, but who knows. Can easy fix if this is the case.

**Comment by abuts** [comment]
fixed through Re #1537
