### ISSUE TITLE
CI Failing on Rocky8 due to HDF versions 

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#1532]
Jenkins pipelines,`PR-Rocky8-2022a and higher` are failing, potentially due to hard-coded library names in CMake file `cmake/horace_findHDF5.cmake`. (C++ variant, not Matlab)

**Comment by abuts** [comment]
fixed by Re #1530

**Comment by abuts** [comment]
addressed using PR #1530. If (when) we decide to write pixels in hdf, other ticket which addresses this should be issued
