### ISSUE TITLE
smooth breaks consistency between pixels and image

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1583]
smooth algorithm works well on `dnd` object making image more pleasent to eye. 
When it is applied to `sqw` object, it chagnes image only so `recompute_bin_data` would return different result

This is not good as by default it is assumed that pixels and image are consistent between each other. 
`smooth` should be either prohibited on `sqw` or it should change `PixelData` to be consistent with image.

**Comment by tgperring** [comment]
Perhaps the best thing is to output a dnd object, not an sqw object? That way we avoid the inconsistency problem, and then interpolating pixels, which would contravene the independence of the pixel data.

**Comment by abuts** [comment]
Or may be just return `DND`. The question is do we need smooth pixels for any purpose

**Comment by tgperring** [comment]
That's exactly what I meant.

**Comment by abuts** [comment]
Do we need smooth pixels? If we just use resulting dnd in binary operations and plotting then certainly not. But if one wants something more advanced, like change pixels not by setting them all to image values but modifying according to some law (e.g. multiply them by some walue to have pixels avarage in cell equal to cell signal or smooth with something like option `-set_pixels` in remplicate) than it may be beneficial to modify pixels too. 

I do not see such requests at the moment but may be @tgperring does.
