### ISSUE TITLE
H3 parallel settings

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1613]
Guidelines for H3 now incorrect for parallel, need updating. H4 may be OK

**Comment by abuts** [comment]
I had a look at the documentation and can not find old recommendation. This is where for symmeterizing whole sqw one should use 15-16 workers rathere than 8. It looks like the user who was complaining about old settings took some old documentation like wiki from web cache. 

Probably this ticket is invalid

**Comment by cmarooney-stfc** [comment]
Issue from old docs not now current, current is fixed
