### ISSUE TITLE
Pixels not fully transformed in cut_sym

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#1620]
Currently `cut` with symmetry does not transform the pixels when they are rebinned in a symmetrised cut. This means that the pixels are binned appropriately, but the connection between pixels and image is broken.

The solution to this is to pass the symmetry operations all the way through to `cut_accumulate_data_` which should transform the pixels following the cut akin to how `symmetrise_sqw` transforms the pixels.

**Comment by abuts** [comment]
A projection uses generic `bin_pixels`  and generic `transform_pix_to_img` to bin pixels
`pix_transformed = obj.transform_pix_to_img(pix_candidates);` 
`transform_pix_to_img` should be modified to form:
`[pix_transformed,pix_candidates] = obj.transform_pix_to_img(pix_candidates);` 

and if projection has symmetry operation attached to it (in additional property), `pix_candidates` should be transformed using symmetry too. 

Alternatively,  overload `line_proj`  to `line_proj_rotation` & `line_proj_folding`  which have these methods specialized.
