### ISSUE TITLE
some scripts from `user_docs\docs\example_scripts` would not work with Horace-4

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1646]
I've noticed that crystal alignment scripts there would not work for Horace-4. Its Horace-3 alignment script.
May be other also would not work -- need careful verification.

**Comment by oerc0122** [comment]
It would be helpful if you described which ones and what errors.

**Comment by abuts** [comment]
I've noticed only alignment incorrect. Need to look at others.

**Comment by abuts** [comment]
Fixed on IDAAAS, Horace-3 scripts copied in their own folder and Horace-example scripts updated to Horace-4 recommended
