### ISSUE TITLE
Remove SQW detpar block and replace with IX_* classes

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#185]
The data currently contained in the SQW `detpar` block is moving to the `Experiment` class's `IX_*` member data.

Output:
- [ ] removal of detpar data block from SQW
- [ ] update of all code references to pull data from the appropriate `Experiment` attribute
- [ ] update load/save SQW to handle new data

Part of #21

**Comment by cmarooney-stfc** [comment]
Closing this as it is superseded by #959 fixed by #999
