### ISSUE TITLE
Re-enable test_tobyfit_refine_crystal_1

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#188]
**Outputs:**
- Re-enable test_tobyfit_refine_crystal_1
- Tests pass locally and on servers

**Comment by abuts** [comment]
nothing to do with #195  -- the test still fails

**Comment by hsautessella** [comment]
I just ran `test_refine_crystal_1` on your branch and it passes

**Comment by abuts** [comment]
I tried, it was failing for me
But if it fixed, this is very good
