### ISSUE TITLE
 Remove detPar and map onto IX_xxx class data

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#191]
The `sqw.detpar` structure contains information about detectors and instrument configuration.

This data should be mapped onto IX_detector, IX_Instr and IX_Experiment classes (where possible) and gaps identified which will be populated with additional data collected externally (e.g. via #226)

Part of #21

**Comment by hsautessella** [comment]
Blocked waiting on https://github.com/pace-neutrons/Horace/issues/288
