### ISSUE TITLE
Horace file access is reininitialized with wrong file name. 

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#194]
Recent changes to sqw file accessors made accessors activated when object initialized by a structure with defined filename and when the file exists. This contradicts the old behaviour, when sqw file accessors been already activated. In this case, a reactivation occurs and the file becomes reactivated with old file, if, e.g. target file was copied from other existing file. 
This is clear bug, which should be fixed.

**Comment by nickbattam-tessella** [comment]
Related to #169

**Comment by hsautessella** [comment]
Seems to be the issue with #188

**Comment by abuts** [comment]
fixed
