### ISSUE TITLE
Convert Horace and Herbert user documentation to reStructuredText

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#203]
The user documentation is hosted on the ISIS Wiki [http://horace.isis.rl.ac.uk/Main_Page](http://horace.isis.rl.ac.uk/Main_Page)

The current Wiki content should be extracted and converted to reStructuredText (`rst`) files.

Outcome
- [x] Folder of Horace user documentation

**Comment by nickbattam-tessella** [comment]
Horace Wiki content (extracted 22 May 2020) [horace.txt](https://github.com/pace-neutrons/Horace/files/4721703/horace.txt)

**Comment by oerc0122** [comment]
This has been completed and is currently in the `horace-docs` repo.
