### ISSUE TITLE
Investigate releasing Horace as a MATLAB toolbox

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#221]
The established Horace/Herbert distribution channel requires users to download via the Horace wiki or directly from GitHub.

MATLAB includes support for packaged code via toolboxes.

This time boxed ticket is to investigate whether it is technically possible to release Horace though this mechanism.

**Comment by nickbattam-tessella** [comment]
@tgperring will make final decision is this is a release path we want or need to support

**Comment by mducle** [comment]
[Done!](https://github.com/pace-neutrons/pace-matlab/)

Not in file-exchange yet - will be uploaded after more extensive testing.
