### ISSUE TITLE
Spike: PixelData file-backed access design

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#225]
Time boxed task to design how the file-based access will work:
- where to the file attributes live
- how to call the existing code
- what new code needs writing etc...

Outcome:
- plan of how to implement the file-backed access

**Comment by nickbattam-tessella** [comment]
Required for #224

**Comment by hsautessella** [comment]
Decisions for first iteration of file-backed process:

- provide either file accessor or name `PixelData` constructor
- keep a file accessor on the `PixelData` object
- provide getter API similar to in-memory operations
- throw errors if attempting to use setters in file-backed case
