### ISSUE TITLE
Extract Horace help from Wiki

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#227]
The existing Horace/Herbert documentation is on an internally hosted Wiki.

The discussion around #124 agreed this content will be migrated to rst hosted externally.

Output:
 - [x]  Existing Wiki markdown extracted 
 - [x]  Wiki markdown converted to rst (#203)
 - [x]  Converted documentation stored in GitHub

**Comment by nickbattam-tessella** [comment]
As per #124 the format conversion can be largely automated.

**Comment by nickbattam-tessella** [comment]
[wikipages.zip](https://github.com/pace-neutrons/Horace/files/4667081/wikipages.zip)

**Comment by nickbattam-tessella** [comment]
Content should follow the style guide (where applicable): https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html

**Comment by oerc0122** [comment]
This should now be mostly fixed in the `horace-docs` repo  [https://github.com/pace-neutrons/horace-docs](url)
