### ISSUE TITLE
gen_sqw - combine pixels

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#230]
Parallel multiple reader/single writer application with extensive inter process communication

Prototype implemented in MATLAB and file-based MPI

Part of #22
After #229 

Output
- [ ]  C++ implemenetation
- [ ] resolve issues with current implementation on Windows machines
- [ ] Test verifying behaviour is is the same between all implementations

**Comment by cmarooney-stfc** [comment]
@oerc0122 Jacob to determine prioritisation based on his Epic

**Comment by cmarooney-stfc** [comment]
closed as long since fixed
