### ISSUE TITLE
Remove access to PixelData internal data array

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#234]
The PixelData API (created in #219) included a public `data` attribute that exposed the internal array.

This breaks encapsulation and should be removed.

All uses should be identified and reviewed:
- can the operation be moved into PixelData class as new API method
- is the operation necessary

**Comment by nickbattam-tessella** [comment]
`sqw\utilities\sort_pix`: 
- sorting code can be moved into a new `PixelData.sort_pixel` method

**Comment by oerc0122** [comment]
Done with refactor
