### ISSUE TITLE
Move pixel operations into PixelData class

### ISSUE THREAD

**Issue by ghost** [pace-neutrons/Horace#238]
There are several functions/operations that act on pixel data. These functions should be moved into the `PixelData` class. Any calls to these function should be replaced to call the new PixelData method. The functions are:

- [x] pix_range:
 (min/max of q-dE coordinates). Can it be cached property, calculated on first request and reused? May be not or maybe it should be defined on creation. And replace all call to pix range in the code to this method. I would calculate it on creation if it is not very expensive.

- [ ] Sort pixels by bin:
getting bins and returning signal and errors by bins and may be pixels sorted too. Should update object with resorted pixels if requested (the object itself appears in LHS)

- [ ] get_pix with transformation matrix as input:
to be extended to transformation function and modified with alignment matrix internally in the future.

**Comment by oerc0122** [comment]
Closed as considered done with PixelData splitting and refactor
