### ISSUE TITLE
Remove `spinw` integration code

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Horace#243]
Initially the implementation of the SpinW within Horace was done on the Horace side with several functions in the `utilities` and `functions` folders - some of which are copies of equivalent SpinW functions. This was because the functions were needed quickly for a training course and had not passed review in SpinW and so was not included in the SpinW distribution.

Since then, however, the interfacing functionality has been implemented in a much cleaner fashion within SpinW and does not require these functions any more (although they still work, and there are unit tests for this functionality in Horace - mostly not run since it needs both Horace and SpinW installed).

Since the philosophy for PACE is that Horace should present a uniform API to third party code rather than implement specific bindings to each, and the Horace/SpinW interface functionality is now included in SpinW, the legacy SpinW interface code in Horace should be removed.

**Comment by nickbattam-tessella** [comment]
Related to #129
