### ISSUE TITLE
Review Horace documentation

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#245]
The Horace documentation will be updated and extended as part of the PACE project.

This ticket is to review the current content, considering:
- is is complete and correct
- are any examples useful for the new Horace
- identifying areas where additional help needs to be written

Relates to issue #124, #203 

Outputs
- [ ] List of required document text updates
- [ ] List of example code fragments that need to be updated for new Horace

**Comment by nickbattam-tessella** [comment]
A broader review of documentation is being carried out by @g5t with the excitation group. This is blocked until that activity is completed.

**Comment by cmarooney-stfc** [comment]
added @oerc0122  as he is otherwise dealing with documentation - probably this ticket is superseded and can be closed

**Comment by cmarooney-stfc** [comment]
superseded by #1238
