### ISSUE TITLE
PixelData - Implement file-backed binary operations

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#249]
Update SQW binary operations to handle large data

Part of #224

Output

- [x] SQW binary operations support large PixelData API
- [x] Consistent API for handling of large and small data
- [x] Consistent DND / SQW API

**Comment by hsautessella** [comment]
Blocked by https://github.com/pace-neutrons/Horace/issues/322 - need pixel masking for SQW-DnD binary operations

**Comment by hsautessella** [comment]
Unblocked. #322 merged
