### ISSUE TITLE
User function should always receive column coordinates

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#261]
As part of the work around external sqw interfaces, we have identified that number of Horace functions accept hkl input in the form arrays with more then one dimension (the shape of the arrays is defined as the shape of DND object, the funcion is applied on). 
This is inconvenient to users and the developers of the external interfaces, so the user function should accept only 1D hkl arrays.

**Comment by hsautessella** [comment]
Closed by #309
