### ISSUE TITLE
gen_sqw single interactive poor man MPI job hangs up on isiscompute on large sqw files

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#279]
The job, run using single parallel worker using Herbert MPI framework hangs up after processing 80~120 nxspe files if run on isiscompute server. 

The reason certainly not in MPI framework itself, as if the log messages are completely disabled, it hangs up anyway. 
The issue reminiscent of early identified on the same server issue when serial job productivity was failing 10-100 times after processing approximately the same number of files. 

The complexity to the issue is added by the fact that similar job run by Matlab MPI framework completes successfully. 

Possible reason is that after Matlatb 2018a, such job are recommended to run with -batch command and not with -r command as it currently done now. But simple change -r to batch does not work. 

Way to reproduce:
Run profile_machine script from Horace performance tests with 'herbert1 framework (poor man MPI), one parallel worker and 250 contributing files. 

The problem is currently largely artificial, as nobody would run such job in such configuration, but can show problem in a future.

**Comment by oerc0122** [comment]
ISIS compute irrelevant
