### ISSUE TITLE
Move configuration updates for tests into setup/teardown methods

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#286]
Horace config is updated during a number of the unit tests. For MPI framwork tests this data must be persisted in order for the workers to pick it up when they launch.

The current implementation does this configuration update inside the test methods; this is slow as it is repeated for each test. Additionally the changes are not restored until after all tests have completed. This is resulting in a number of Horace tests timing out. 

The configuration updates should be moved into class setup/teardown methods so they are only done once.

**Comment by oerc0122** [comment]
Overridden by #965
