### ISSUE TITLE
Rewrite SQW as new-style class

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#288]
The SQW/DND objects are implemented as old-style MATLAB classes. As a part of the refactoring effort these should be restructured to be "new-style" classes.

- [x] create abstract SQWDnD base class 
- [x] create concrete SQW class (#422)
- [x] create abstract DND base class
- [x] create concrete D2D class (#424)
- [x] create concrete DnD classes 
- [x] test cases all pass

The new object still requires removal of detpar and replacement with the IX_xxx instrument classes, but that is dealt with separately by ticket #191. Hence this can now be closed.

Part of #21

**Comment by nickbattam-tessella** [comment]
Work done on `288_sqw_rewrite_feature` branch

**Comment by cmarooney-stfc** [comment]
@nickbattam-tessella Hi Nick - This is a general question for the group but I could start with you for this one. Process question. We have a procedure for reviewing PRs. But this is a ticket in for review. At what stage does it go to review? At first PR? After last PR? And when does review get changed to done? Thanks
