### ISSUE TITLE
TestCombineSQW::Normal_Expand_Mode_Threads occasionally hangs

### ISSUE THREAD

**Issue by ghost** [pace-neutrons/Horace#300]
Every so often the test will hang and timeout. Adding any print/debugging statements seems to stop the test from hanging. 

This issue may also have been spotted in production.

To reproduce the issue:
- build Horace: `./tools/build_config/build.ps1 -build`
- cd into the build folder `cd build`
- run the test until it fails ` ctest -C Release -R combine_sqw -VV --repeat-until-fail 250` (I've found 250 times is usually enough to elicit the failure)

Tested on Windows

**Comment by abuts** [comment]
the issue is partially addressed in #302, where failure due different reason looks like hung up. But the threads can still hung for different reasons.

**Comment by oerc0122** [comment]
Threads is fixed
