### ISSUE TITLE
Dependency management plan

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#31]
C++ build will include dependencies on a number of third-party libraries, e.g. boost, mpi, hdf5, testing framework...

Output:
- A plan for managing this should be created and filed as an ADR

**Comment by nickbattam-tessella** [comment]
MATLAB enforces strict versioning of libraries, often not-current releases.

As part of this investigation into dependency management we must find a solution to map the correct library to the required MATLAB version

e.g.
- HDF5 1.8.12 for <current releases of MATLAB>
- HDF5 1.8.6 for <legacy releases of MATLAB> TODO: confirm WHICH version
- build against HDF5 libraries found on the MATLAB path for Linux
- build against HDF5 libraries managed locally for Windows as the MATLAB doesn't include the static libraries
- FAIL the build if the required headers or libraries matching the found MATLAB version don't exist

There is no simple reference on the Mathworks site for which MATLAB releases are shipped with which library.

**Comment by hsautessella** [comment]
As part of this ticket, we should also look into how we deal with other PACE dependencies and modelling codes, e.g. [Herbert](https://github.com/pace-neutrons/Herbert) and [Euphonic](https://github.com/pace-neutrons/Euphonic)

**Comment by nickbattam-tessella** [comment]
Time boxed based document decisions based on current understanding

**Comment by hsautessella** [comment]
Closed by #132
