### ISSUE TITLE
Write SMG for running/debugging C++ tests

### ISSUE THREAD

**Issue by ghost** [pace-neutrons/Horace#315]
To run tests that use Matlab libraries on Windows, Matlab's DLL directory must be on the path. This is not documented anywhere except in CMakeLists files. An SMG should be written detailing what needs to be done to get the tests running on Windows and how to debug them in Visual Studio.

**Comment by nickbattam-tessella** [comment]
Relevant to: https://github.com/pace-neutrons/Herbert/issues/213

**Comment by oerc0122** [comment]
Done, see smg `05_adding_and_running_cpp_unit_tests.md`
