### ISSUE TITLE
C++ unit testing

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#32]
Identify the most appropriate C++ testing library and migrate any existing tests to this.

Outputs:
- ADR documenting selection
- Implementation of at least one test

**Comment by hsautessella** [comment]
Googletest was identified as the preferred choice for testing framework.

1) It is in active development - receiving bug fixes
2) It is in use by other teams within ISIS (IBEX, Mantid uses it for the built-in mocking framework)
3) It is required by [Google Benchmark](https://github.com/google/benchmark#requirements) which may become useful in the future.

The fact that it was in use by other teams within ISIS outweighed the fact that Catch2 is more light-weight.

**Comment by abuts** [comment]
Bearing in mind that the only unit tests currently existing for C code are the tests for CombineSQW, do not see any problem in changing to this. 

Matlab code tests should be still written on the basis of matlab_xunit  tests framework
