### ISSUE TITLE
Add PixelData page size config option

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#320]
A config option should be added that allows the user to set the page size for `PixelData` objects. Some care will need to be taken as this setting could result in having two separate `PixelData` objects with different page sizes. The differing page sizes will likely interfere with binary operations between the two objects.

**Output:**
- A `hor_config` option `pixel_data_page_size` (or similar)
- Some guarantees in behaviour when `PixelData` objects with different page sizes interact. We could:
    - not allow changing the page size setting if a file-backed `PixelData` object exists
    - change the page size of existing `PixelData` objects when the setting is changed
    - adapt binary operations between `PixelData` objects such that they're not dependent on page size

**Comment by abuts** [comment]
I think, adding appropriate option to hor_config would be sufficient. blocking changes if pixData objects exist (instance counter!) is also straightforward.
