### ISSUE TITLE
Multifit tests use the now obsolete multifit and/or fit syntax

### ISSUE THREAD

**Issue by tgperring** [pace-neutrons/Horace#325]
Many of the multifit tests in Horace and Herbert use the legacy - now obsolete - calling syntax. These need to be converted to use the object-oriented multifit syntax.

Many multifit tests also use the legacy - now obsolete - fit methods. Users should be directed to use multifit instead rather than to the legacy function.

**Comment by nickbattam-tessella** [comment]
Related to https://github.com/pace-neutrons/Horace/issues/312

**Comment by nickbattam-tessella** [comment]
Herbert issue: https://github.com/pace-neutrons/Herbert/issues/217
