### ISSUE TITLE
Initial configuration for Horace installation 

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#326]
The Horace/Herbert code requires manual setup/configuration before it can be run. If this is not done (correctly) the user will get cryptic errors.

The process should be clearly and simply documented so any user can see exactly what files need to placed where and how the MATLAB path should be updated.

As much as possible should be scripted via MATLAB, or a set of platform-specific shell scripts.

Setup should is needed for users installing "releases" (i.e. zip/tar.gz files including binaries downloaded from GitHub) and for developers with local checkouts of the source. 

It is acceptable for the 'developer' workflow to require a higher level of knowledge and additional manual steps.

**Comment by abuts** [comment]
this has been fixed by introducing horace_install script
