### ISSUE TITLE
Use tempname function for PixelData tmp files

### ISSUE THREAD

**Issue by ghost** [pace-neutrons/Horace#328]
The current PixelData tmp folder name (`sqw_pixNNNNN`), where the number is the random object ID.
There is concern that this is vulnerable to name collisions when there are 100s of SQW objects in use.

This should replaced with a name with a greater likelihood of uniqueness (e.g. a guid-based name).

**Comment by abuts** [comment]
pixel tmp files are deprecated. This ticket is irrelevant
