### ISSUE TITLE
Implement masking for file-backed SQW objects

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#330]
https://github.com/pace-neutrons/Horace/pull/329/ implemented a `mask` method for pixels. The `sqw` object's `mask` method should be updated to call `PixelData.mask`.

It may be more efficient if the new `urange` is calculated within `PixelData.mask`, so we avoid looping through pixel pages twice.

**Comment by nickbattam-tessella** [comment]
Method implemented but has resulted in TobyFit tests failing. Logs show a different initial guess is generated for the model which diverges.
