### ISSUE TITLE
Create Release CI Pipeline

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#331]
~This is a new meta-job that will trigger BRANCH builds on ALL platforms of the REL_x_y Horace branch against the REL_m_n[_o]
tag or branch of Herbert~

~These two parameters will be specified explicitly as parameters.~

Create a `Release-*` pipeline for each of the platforms/Matlab versions we support. These pipelines should require two parameters from the user when they are triggered: the name of the Horace branch and the name of the Herbert branch to build/test. This will allow us to build release branches of Herbert/Horace.

Depends on: #332 

**Outputs:**

- New Jenkins pipelines that will take Horace REL_-branch name and Herbert REL_-branch name or REL-tag as parameters
- A `Release-Trigger` pipeline that will trigger all the `Release-*` pipelines
- Updated SMG sections on releases to mirror the new workflow

**Comment by hsautessella** [comment]
Blocked waiting on #348

**Comment by hsautessella** [comment]
Blocked waiting on #363

**Comment by hsautessella** [comment]
Closed by https://github.com/pace-neutrons/Horace/pull/362 and the creation of Horace release pipelines in Jenkins GUI
