### ISSUE TITLE
Optimize mask(SQW)

### ISSUE THREAD

**Issue by ghost** [pace-neutrons/Horace#339]
Masking of SQW objects with file-backed pixels was implemented in https://github.com/pace-neutrons/Horace/pull/338. At the moment `mask` does 2 loops over the file-backed `PixelData` instance: one loop in `PixelData.mask` and then another in `recompute_urange`. 

We can reduce the runtime of the algorithm by performing `recompute_urange` within the loop performed in `PixelData.mask`. This would simply involve keeping track of the upper and lower-bounds of each quantity in `PixelData.coordinates` for each page of data looped through in `PixelData.mask` as pixels are removed.

**Comment by oerc0122** [comment]
Ont-the-fly range computation is done
