### ISSUE TITLE
Update permute_pix_array for file-backed pixel data

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#345]
Update: Delete `permute_pix_array` function and `sqw.to_slice()`

~The `permute_pix_array` function needs to be updated such that it does not assume that all pixel data is held in memory.~

~An example of how to loop through pixel data is given in: https://github.com/pace-neutrons/Horace/blob/master/horace_core/sqw/PixelData/%40PixelData/private/compute_bin_data_mex_.m.~

Part of #250 

**Outputs:**
- [ ] `permute_pix_array` deleted

**Comment by nickbattam-tessella** [comment]
This functionality is in slice, and the function is not required any more.

**Comment by cmarooney-stfc** [comment]
Closed following PR merge to fix
