### ISSUE TITLE
Manage version number for builds and releases

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#35]
Create managed release number to replace legacy SVN based numbering e.g.:
m: major
n: minor
o: bugfix
p: datetime (yyyymmdd-hhmmss)

p to be added at automatically at buildtime; m,n,o from developer managed version text file.

**Comment by nickbattam-tessella** [comment]
`horace_init` currently prints two SVN-style revision numbers and datetime:
```
! Matlab  code: $Revision:: 1758 ($Date:: 2019-12-16 18:18:50 +0$) !
! Mex files   : $Revision:: 1757 ($Date:: 2019-12-05 14:56:06   $) !
```

The majority of Horace and Herbert source files include a revision number at the end of the header:
```
% $Revision:: 1758 ($Date:: 2019-12-16 18:18:50 +0000 (Mon, 16 Dec 2019) $)
```
injected by `horace_core\admin\horace_version.m` and `herbert_core\admin\herbert_version.m`.

Since the move to Git the version should now be datetime, sha or tag-based.

**Comment by nickbattam-tessella** [comment]
A version number is included in the CI built package names; this must be consistent with the version number reported by `[horace|herbert]_init`

**Comment by nickbattam-tessella** [comment]
Historically the version headers were injected with a TortoiseSVN commit hook. 

This has been replaced with the `update_svn_revision_info.m` function in `Horace\admin` called from `make_horace_deployment_kit` on both Herbert and Horace source files.

**Comment by hsautessella** [comment]
Following https://github.com/pace-neutrons/Herbert/pull/108, the templates in Herbert have moved. This means we'll need to update the `FindHerbert.cmake` script to find those files in their new directory
