### ISSUE TITLE
Document testing strategy

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#37]
It is essential that the updates to Horace

i) do not break existing functionality
ii) returns the same results when run in single threaded, multi-threaded (shared memory), and fully distrusted environments
iii) is performant and that performance scales

Outputs: Test Plan document.

**Comment by Kevin-Woods-Tessella** [comment]
Initial draft looks good.  Let's publish it and update it as the project evolves.
