### ISSUE TITLE
Jenkins build artifacts labelled with wrong SHA

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#375]
Build artifacts from Jenkins builds seem to be getting labelled with the wrong SHAs sometimes.

**PR- pipelines:**
For example [this build's](https://anvil.softeng-support.ac.uk:444/jenkins/job/PACE-neutrons/job/Herbert/job/PR-Scientific-Linux-7-2018b/485/) artifact should be labelled with SHA `453e46f` (the head of the pull request branch) but is instead labelled with `03cbbce` (which is the first non-merge commit in master).

We intentionally ignore merge commits when we parse the SHA to label the build with, as we wanted to avoid labelling the build artifact with a merge commit created by merging the PR branch into master. This may need to be re-considered.

**Master pipelines:**
For example [this build](https://anvil.softeng-support.ac.uk:444/jenkins/job/PACE-neutrons/job/Horace/job/Scientific-Linux-7-2018b/133/) should be labelled with SHA `8a8fed` but instead has `9a4d453`. This is because we're ignoring merge commits.

The code dictating what SHA the builds are labelled with is [here](https://github.com/pace-neutrons/Herbert/blob/ebeaa8136a58f0cded9dcfdbd7fd9bdbd4aabdda/cmake/shared/PACE_Version.cmake#L53).

**Comment by nickbattam-tessella** [comment]
For the `master` and `branch` pipelines the code should be modified to remove the `--no-merge` directive. In these cases we want the SHA of the commit we're building.
