### ISSUE TITLE
PixelData - update sort_pix

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#398]
The `sort_pix` function in `horace_core/utilities` should be updated to handle the `PixelData` object.

There's a decision to be made on whether `sort_pix` should act on the whole pixel array or only the current page (in which case the caller would be responsible for looping). Whichever decision is made, this function should become a method of `PixelData`.

Child of #250

**Comment by nickbattam-tessella** [comment]
Closed - no-longer relevant, see parent ticket
