### ISSUE TITLE
Verify mex-files are cross-version compatible

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#40]
The mex files are build with a specific release of Matlab and C-compiler.

We should verify that an file built with a specific Matlab (e.g. Matlab 2019a) and be used by other releases, e.g. Matlab 2018a.

This should be tested for 2019 -> 2018 and 2018 -> 2019.

**Comment by oerc0122** [comment]
Considered unnecessary as should be built for machine run
