### ISSUE TITLE
Add transform sqw to the list of symop methods

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#402]
Currently symop works together with cut_sqw_sym to build symmetrized cuts.  It would be beneficial for testing, code maintenance and cases where particular cuts need special treatment before combining  to be able to apply particular symmetry to the whole sqw object

CM 19/9/23: first sentence is no longer correct according to Alex

**Comment by cmarooney-stfc** [comment]
@oerc0122 Jacob to prioritise for his Epic based on his draft PR

**Comment by cmarooney-stfc** [comment]
@oerc clarify what transform sqw means. Is it a function or a keyword in gen_sqw (see Alex)

**Comment by cmarooney-stfc** [comment]
decide to close. Other issues may pick up on the theme
