### ISSUE TITLE
Add support for PixelRanges to put_pix

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#420]
Related to #389 

The put_pix function is called as part of the SQW save operation to write the raw pixel data to file.

This allows the caller to specify a range of pixels to write. There is a conversation that needs to be had about whether that range should index into the current page of pixels, or into the full pixel array, and what the implications of both options are.

Outcome
- [ ] decision on relative vs absolute indexing
- [ ] paged implementation of the algorithm supported agreed indexing

**Comment by hsautessella** [comment]
Closed by #403
