### ISSUE TITLE
Update file readers

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#423]
The `read_sqw` and `read_dnd` methods is are wrappers around a generic `read_horace` SQW file loader that will return an cellarray of SQW and/or DND objects from an array of input filenames 

The heavy lifting is done via file loaders returned from the static `sqw_formats_factory` class.

These must be updated to work with the new SQW and DND class constructors.

- [ ] updated `read_horace(...)` method returning cell array of SQWDNDBase objects.
- [ ] updated `read_dnd` method returning DnD class object
- [ ] updated `read_sqw` method return SQW class object

**Comment by abuts** [comment]
this has been completed with new sqw design.
