### ISSUE TITLE
Create Linux CI build

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#43]
Create a Jenkins build and test job for the LINUX build.

Part of #30 

Output:
- bash script to build and test
- jenkins script to conditionally run 
- jenkins configuration to trigger builds

**Comment by nickbattam-tessella** [comment]
Blocked waiting for plugins to be installed on ANVIL: 
•	Generic Webhook Trigger https://plugins.jenkins.io/generic-webhook-trigger - Allows GitHub to trigger builds
•	httpRequest https://plugins.jenkins.io/http_request - Send GitHub statuses
•	xUnit https://plugins.jenkins.io/xunit - Test parsing and visualisation
•	Rebuilder https://plugins.jenkins.io/rebuild - Rebuild failed builds
•	Blue Ocean https://plugins.jenkins.io/blueocean - Better pipeline construction and visualisation 
o	  Including Git Pipeline for Blue Ocean and GitHub Pipeline for Blue Ocean
•	Delivery Pipeline https://plugins.jenkins.io/delivery-pipeline-plugin - Multi-job pipeline and deployment visualisation
•	Performance https://plugins.jenkins.io/performance - Display and track benchmarking results
•	Warnings Next Generation https://plugins.jenkins.io/warnings-ng - Parse and display warnings from builds

**Comment by hsautessella** [comment]
Removing blocked label, all plugins above except httpRequest and Blue Ocean have been installed. 

There are plans to install blue ocean down the line
