### ISSUE TITLE
Implement file-backed versions of algorithms

### ISSUE THREAD

**Issue by ghost** [pace-neutrons/Horace#434]
A set of Horace algorithms needs to be updated to work with file-backed pixel data. The API for the algorithms should follow the design decisions laid out in the ADR written in https://github.com/pace-neutrons/Horace/pull/416.

File-backed `PixelData` objects should be used when paging over pages of pixel data. For performance reasons the implementations should try to minimize the number of loops over the data as these operations are expensive. Care should also be taken to not "leak" file-backed objects and expose them to users.

**Outputs:**

File-backed implementations of the following algorithms:

- [x] `gen_sqw`
- [x] `cut` https://github.com/pace-neutrons/Horace/issues/441
- [ ] fixing cut performance and filebased cuts (large cuts do not work) https://github.com/pace-neutrons/Horace/issues/691
- [x] `func_eval` #534 
- [x] `sqw_eval` #550
- [x] `multifit`
- [x] `tobyfit`
- [ ] #989
- [ ] #990

**Comment by hsautessella** [comment]
Blocked by https://github.com/pace-neutrons/Horace/issues/435.

**Comment by nickbattam-tessella** [comment]
supersedes #250
