### ISSUE TITLE
Create Windows CI build

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#44]
Extend the Linux build (#43) to build and test on Windows

Part of #30 
Depends on #39 

Output:
- powershell script to build and test on Windows
- jenkins script to conditionally call the Windows script

- [x] Herbert https://github.com/pace-neutrons/Herbert/issues/65
- [x] Horace

**Comment by hsautessella** [comment]
Closed by #115, #119 and https://github.com/pace-neutrons/Herbert/pull/44
