### ISSUE TITLE
Implement cut with file-backed pixel data

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#441]
The `cut` algorithm should be updated so that the file-backed implementation uses file-backed `PixelData` objects when operating on pixels. 

Some follow-up tickets to this include:
- Ensuring the API for `cut` matches the one defined in the ADR written in #416.
- Moving cut out of the `sqw` object and into `horace_core/algorithms`.

Three pieces:
- [x] file-memory cut (13pts)
- [x] file-file cut (5pts)
- [x] memory-memory cut (should be covered by file-memory) (3pts)

- [x] performance reoptimization

Child of #434.

**Comment by cmarooney-stfc** [comment]
@hsautessella Hi Harry - for the description, noting that (1) "there are 3 pieces" and 4 boxes (2) that none are ticked. Could you edit or update as appropriate please?
