### ISSUE TITLE
Documentation Jenkins Pipeline

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#455]
- [x] Nightly (unstable) & Release (stable) -> Push
- [x] Release docs separately in release pipeline as separate zip artifact
- [x] Build docs at release draft for review
- [x] Split scriptable elements out of the Jenkinsfile into separate files
- [x] Create zipped HTML artifact for checking MRs
[~] On each PR build and run docs w/ tests (item now moved to separate ticket #458).
- [x] Update documentation version no on release
- [x] Have stable (last github release), unstable (master [Nightly]), version (e.g. 3.5.1)
- [x] Stable link through HTML Redirect

**Comment by cmarooney-stfc** [comment]
@oerc0122 Hi Jacob - this is in the sprint backlog but I can see some work items have been done. Should this be in "In Progress"?

**Comment by oerc0122** [comment]
Already have doc tests issue #458.

**Comment by cmarooney-stfc** [comment]
@oerc0122 Hi Jacob, noting that the "On each PR build and run docs \w tests" item is not ticked. SHould this be still in progress? thanks Chris

**Comment by oerc0122** [comment]
No, as noted in my closing comment, that is documented under issue #458 , and should be considered a separate issue in the Epic.

**Comment by cmarooney-stfc** [comment]
True, but just looking at the issue description, it's not obvious to go down and find your comment. I've added "item now moved to separate ticket" in the issue description - please could you check this is ok? thanks
