### ISSUE TITLE
Document the changes in behaviour in cut

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#463]
The changes under ticket [#443](https://github.com/pace-neutrons/Horace/issues/443) have introduced some change in behavior. This changes have to be documented within the release notes.

**Comment by nickbattam-tessella** [comment]
Why has the documentation folder moved?

**Comment by abuts** [comment]
Old documentation, which is related to the pre-project development and gets less relevant to new Horace and  has been moved to old_documentation not to clog-up the recent documentation.
