### ISSUE TITLE
Create dirty flag for property changes on PixelData objects 

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#471]
After executing set operations on a PixelData object the PixelData and containing SQW object may be left in an inconsistent state, e.g. uranges, image pixels will not match the raw pixels in the PixelData object.

The PixelData object contains a dirty-flag at the page level. This is set by all calls to property set methods and is used to direct the page loading to a tmp file (for dirty pages) or the original data file (for clean)

An new whole-PixelData level dirty flag is required which is set on any set operation and cleared when the SQW and PixelData classes have been updated to match the new information. Clearing this does not clear the page-level dirty flags within the PixelData object.

Outcome
- [ ] PixelData whole object dirtyflag
- [ ] PixelData "make self consistent" method to recalculate all PixelData-level data derived from the raw data
- [ ] SQW class handling of dirty PixelData
- [ ] new SQW class "make self consistent" method to recalculate all SQW-level data derived from raw data
- [ ] warning displayed on access to any dependent data if PixelData object is dirty
- [ ] PixelData dirty flag cleared by successful update of all derived SQW and PixelData data 
- [ ] PixelData dirty flag may be manually cleared with "here be dragons" warnings in method

**Comment by oerc0122** [comment]
Single filebacked refactor renders irrelevant
