### ISSUE TITLE
create static Horace distribution

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#5]
This is a placeholder ticket for the people, who would create a standalone horace distribution kit (zip file), i.e. run create_horace_deployment_kit. The script now involves running update_svn_repository_info('horace'), which modifies number of Horace files, containing svn revision info. 
In addition, one may want to run update_svn_repository_info('horace') itself. 

As these causes numerous trivial changes to multiple Horace files. For clarity, all these changes should be committed under this ticket.

**Comment by hsautessella** [comment]
Now that we have a different packaging/release process, I think this ticket can be close
