### ISSUE TITLE
Migrate DnD API to new classes

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#507]
Migrate the full (old) DnD APIs to the new DnD classes, excluding the 'fit' functions.

Follows #490 

Outcome:

- [x] All DnD methods implemented on new class (D2D)
- [ ] All DnD methods implemented on new class (D0D, D1D, D3D and D4D)
- [ ]  Simple tests implemented to verify all methods can be executed

**Comment by nickbattam-tessella** [comment]
This ticket includes the removal of identical duplication of SQW and DnD implementations of functions, moving the code to the `SQWDnDBase` class where possible. This should allow the removal of the current implementations in DnD which cast from DnD to SQW, execute the SQW function and cast the result back to the appropriate DnD class

**Comment by cmarooney-stfc** [comment]
First checkbox should be DnD

**Comment by cmarooney-stfc** [comment]
Also not sure your checkboxes correspond to the first comment after the description
