### ISSUE TITLE
Use Warnings Next Gen plugin for CppCheck results on Jenkins

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#547]
The [Warnings-NG](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md) plugin is more modern and feature-rich than the `CppCheck` plugin. Warnings-ng can do things like: aggregate results with other warnings/static analyzers (e.g. GCC or mlint warnings), show the warnings in the context of code snippets and perform Git forensics (see docs). You can also set a "baseline" warning level, such that any builds that have over a given number of warnings will fail.

**Comment by nickbattam-tessella** [comment]
Related to #474
