### ISSUE TITLE
Update horace_mex to use CMake defined build

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#57]
The horace_mex.m script provides a simple interface for users to build the backend code from MATLAB

With the creation of the CMake framework (#36) there is logic now duplicated in these two processes.
The MATLAB script should be updated to wrap a call to cmake without changes the user experience.

Output:
- horace_mex script with unchanged (if possible) interface
- horace_mex script with no build logic that uses the CMake build definition (directly or indirectly)
- user documentation on how to add cmake to their system

**Comment by oerc0122** [comment]
Duplicate ticket of #41
