### ISSUE TITLE
Document which builds are affected by which pipeline vars

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#573]
Extend comments of Jenkins pipeline vars to document which builds/pipelines they are liable to affect.

**Comment by cmarooney-stfc** [comment]
@oerc0122 Hi Jacob - Hope this isn't too pedantic. Can you add "which" to the title between document and builds. Otherwise it reads that pipeline vars are affecting document builds, not that you're documenting which builds are affected by the vars. The description is excellent. Thanks
