### ISSUE TITLE
Herbert files missing for Horace tests

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#585]
Horace tests are reporting errors finding Herbert files:
- `Herbert/_test/test_mpi`
- `Herbert/_test/common_functions`

**Comment by nickbattam-tessella** [comment]
It's unclear why Horace tests require these folders -- any common code should be in `Herbert/_test/shared`

**Comment by nickbattam-tessella** [comment]
From `PACE-neutrons/job/Horace/job/Scientific-Linux-7-2019b/143` [horace_test_warnings.log](https://github.com/pace-neutrons/Horace/files/6003055/horace_test_warnings.log)

**Comment by abuts** [comment]
fixed by merging Herbert and Horace
