### ISSUE TITLE
Uninitialized variable in calc_projections_c.cpp

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#605]
CPPCheck reports a **HIGH** warning that `ki` is uninitialized in `_LowLevelCode/cpp/calc_projections_c/calc_projections_c.cpp` where it is used on L.422.

The code path identified is not "valid": this routine does not work for multiple efixed in direct mode, the mode is not supported; multiple efixed can occur in indirect mode only.

Though appropriate setting of the input parameters it is possible to force this code to execute.

Additional Boolean checks should be added to the code to prevent the unintentional execution of this code.

**Comment by abuts** [comment]
Fixed as part of Re #893
