### ISSUE TITLE
Write package install script for users

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#639]
The installation process for users is a bit fiddly, and involves them directly editing variables in `.m` files.

We should write a Matlab `horace_install` script that will do all the necessary file editing/copying. A user should be able to use Horace (including mex and parallel) by performing the following steps:

1. Download the release package from GitHub
2. Extract the package anywhere on the file system they have read access
3. From within Matlab, run `cd <path_to_extracted_release>; horace_install>`
4. Now from any directory, users should be able to run `horace_on` to enable Horace.

**Comment by cmarooney-stfc** [comment]
@abuts @oerc0122 Adding us as reviewers so we can close what looks like a done ticket
