### ISSUE TITLE
Tests disabled in  `test_sqw_file/test_file_input.m` with DnD issues

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#644]
There are remaining issues with read and cut on DnD objects.

These have necessitated the disabling of four asserts in `test_sqw_file/test_file_input.m` (marked with a TODO)

Outcome:
- [x] cut updated to work correctly in dnd and sqw
- [x] read/read_horace update to work with DnD or removed in favour of an alternate read method

Additional outcomes (see comments below 4/5/21)
- [ ] additional calls for test_change_crystal needed
- [x] dnd constructor with 4 vectors input not implemented

**Comment by cmarooney-stfc** [comment]
NOting that the changes about to be merged from the 288 feature branch will largely fix this, but that the more complicated lack of change_crystal for d2d is not yet addressed.

**Comment by cmarooney-stfc** [comment]
Also add to this that in test_dnd/test_dnd_constructors, the default d2d constructor is now activated, but the d2d constructor from 4 vectors after it is not yet supported and has been skipped - it should be fixed in this ticket.

**Comment by cmarooney-stfc** [comment]
CUt and read issues in the top comment addressed by #673 (along with a lot of other things).

**Comment by abuts** [comment]
fixed as part of #892
