### ISSUE TITLE
concat in PixelData may duplicate pixels

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#659]
duplicated pixels, e.g the pixels which come from the same run, detector and energy bin are usually an error if not created for special purpose. 

current PixelData cat function does not make checks for duplicated pixels so may produce incorrect results. A switch, to allow duplicated pixels should be added to cat function and the default behavior for this function should be dropping duplicates. 

Current behavior of the cut function on pixels is physically incorrect.

**Comment by oerc0122** [comment]
Should be fixed with pixeldata refactors
