### ISSUE TITLE
HerbertCPP communicator changes

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#66]
There are changes to Herbert parallel framework and its interfaces which may affect Horace. 
This mainly related to unit tests though other code can also be affected (this cases should be identified and preferably redesigned)

Here we should change Horace according to Herbert CPP communicato changes.
[](url)
Currently it has accomodated changes related to[#28](https://github.com/pace-neutrons/Herbert/issues/28), [#36](https://github.com/pace-neutrons/Herbert/issues/36); and [#6](https://github.com/pace-neutrons/Herbert/issues/6)  tickets

**Comment by nickbattam-tessella** [comment]
Part of #68

**Comment by nickbattam-tessella** [comment]
Closing bucket ticket; further updates will be made on change-specific tickets
