### ISSUE TITLE
Horace GUI doesn't work entirely with nxspe files

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Horace#693]
The Horace GUI was written ~10y ago and has not been updated much since. When it was written, the `nxspe` format was not widely used - instead it assumes the data is in `spe` and requires a `par` file.

It should be updated to allow `nxspe` files.

**Comment by abuts** [comment]
There are mainly Duc's changes plus minor refreshments to GUI to catch and present errors better. 
The identical changes are done to `rel_3_5` (these are cherry-picked from rel_3_5) -- This ticket is some minor GUI refreshment -- may go unchecked.
