### ISSUE TITLE
Handle failed C++ MPI nodes

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#74]
Nodes can fail for a number of reasons:
- user code fails (error)
- user code fails (stall)
- bad data
- node fails
- network fails

These failure modes should all be identified and managed in a way that reports the job has failed and (if where possible) as much information about the reason (e.g. the exception thrown, which data was being processed, which function, which node, ...)

Required for #68

Output:
- code that handles the identified failure modes

**Comment by abuts** [comment]
This is done and works. If something is wrong with it -- its another tickert
