### ISSUE TITLE
Long pauses in MPI Framework slowing short jobs

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#753]
Long `pause`s in the MPI framework are causing short jobs such as those in the tests to take excessively long times (sometimes over 8x as long). As there are many short jobs this effect is strongly amplified. While this should not affect performance in actual use, reducing the testing time is of benefit.

While it may be necessary to pause for checking file status (due to network lag, remote drives, etc.) the host process is doing no work while these checks are taking place and as such increasing the frequency of said checks should not affect correctness of the MPI framework.

Will implement a faster check of completion while maintaining the current `check_time` as the print frequency for the parallel status.

**Comment by cmarooney-stfc** [comment]
@oerc0122 Hi Jacob, presuming PR-He-398 has fixed this - it is merged - can we mark it done now?
