### ISSUE TITLE
Symmetrisation bug for non-orthogonal axes

### ISSUE THREAD

**Issue by russellewings** [pace-neutrons/Horace#762]
Bug discovered by user (Andrew Wildes, ILL): symmetrisation for +/-Q for a non-orthogonal system seems to be done correctly on the pix array, but when final step of data recomputation is performed (using sqw/cut), pixels that should contribute to the signal array are not included. Example code to illustrate the issue available if needed - let me know. A workaround has been found for this user now, but not very satisfactory.

**Comment by oerc0122** [comment]
Will double check with new symmetrise
