### ISSUE TITLE
Feature request (or bug?): extra info printed to Matlab stream during first time read of old sqw file

### ISSUE THREAD

**Issue by russellewings** [pace-neutrons/Horace#785]
I understand that when a cut is being taken from an old style sqw for the first time, the entire file has to be read in order to update certain necessary fields (email conversation with Alex). At present the information printed to screen says "Recalculating actual pixel range missing in file <filename>.sqw". If this is indeed a one-time operation can this be made clear to the user, otherwise it looks like the performance of cut_sqw has tanked. I suggest something along the lines of "Recalculating pixel range missing in file <filename>.sqw - this is a one-time operation affecting the speed of cut_sqw. Future cuts will not be subject to this recalculation and will be much faster".

**Comment by abuts** [comment]
its a bug -- consequence of using file-based constructor on old files
