### ISSUE TITLE
Add Herbert as a submodule within Horace.

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Horace#8]
Horace depends on Herbert. To make this explicit we should add the Herbert repository as a submodule within the Horace repository.

The submodule should be called `herbert` which means renaming the current `herbert` folder which contains overloads of Herbert / Genie-like plot commands to Horace `dnd` data types.

Also the initialization and installations scripts will need to be renamed.

**Comment by abuts** [comment]
I believe we decided not to go ahead with this.
