### ISSUE TITLE
sqw/signal method is missing in 3.6 and newer

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Horace#819]
Horace 3.5.2 and earlier had a [method called `sqw/signal`](https://github.com/pace-neutrons/Horace/blob/v3.5.2/horace_core/sqw/%40sqw/signal.m) which would create a new `sqw` object based on a current object but with the signal field replaced by one of the coordinates. It is meant for computations of things like I/(E/Q^2) [to get an approximation of the density of states].

However, this method has been removed since 3.6.0. It would be good to have it restored. (It is explicitly mentioned in the Horace training course; and was present and working in the last training course in June 2021!)

**Comment by abuts** [comment]
fixed a while ago
