### ISSUE TITLE
redundant dnd constructors

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#824]
old dnd objects have range of various pretty complex constructors. We have replaced them in favor of single simple multi-component constructor reflecting the internal structure of the object. 
Do we need to implement other, more complex and confusing constructors?

**Comment by oerc0122** [comment]
@tgperring  to review

**Comment by abuts** [comment]
as this was sitting here for a year at least and no need in these constructors identified, this issue may be considered closed
