### ISSUE TITLE
Investigate options for removing duplication in Horace and Herbert build and test

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#84]
The Horace and Herbert build pipelines share a number of common elements:
- CMake helper functions
- CPP test framework (googletest) is downloaded and compiled from source
- shared utility functions

This ticket should explore what options are available for removing the duplication and removing the need to repeated compilation of the test library.

Output:
- recommendation of how to share common code and new ticket with details
- recommendation of whether the repeated build of googletest can or should be avoided

**Comment by nickbattam-tessella** [comment]
The idea of having Herbert as a submodule of Horace has been considered previously: https://github.com/pace-neutrons/Horace/issues/8

**Comment by abuts** [comment]
in favour of the ideas that the Herert is a self-consistent module and the Horace has Herbert as a dependency. As such, all common code (i.e. unit test framework) should be placed in Herbert

**Comment by nickbattam-tessella** [comment]
The other option is to extract common (utility) code into a third repository. 

That would allow other PACE projects using `CMake`, `C++`, `googletest`, `MATLAB` to re-use code without depending on all of Herbert.

**Comment by nickbattam-tessella** [comment]
@g5t has use for the CMake helper functions, specifically a find_mp equivalent of the find_hdf function to find the Matlab compatible library.

His current solutions work on Linux and Windows but not MacOS

**Comment by nickbattam-tessella** [comment]
Linked to #43 #44 #47 #30

**Comment by nickbattam-tessella** [comment]
Time boxed activity to document current ideas on the subject

**Comment by hsautessella** [comment]
https://github.com/pace-neutrons/Horace/issues/145 goes a fair way in reducing duplication in terms of CMake scripts. Any common CMake utilities now sit in `Herbert/cmake/shared`, the `FindHerbert` script in Horace then adds that directory to the CMake module path so Horace can use them.

**Comment by hsautessella** [comment]
@nickbattam-tessella do you think #145 closes this?

**Comment by hsautessella** [comment]
Closing since I think #145 covers the purpose of this issue. Common CMake scripts have all been moved into Herbert
