### ISSUE TITLE
unit tests and clarification for replicate_array

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#848]
there are two very different versions or replicate_array function present in Horace and Herbert. Are these versions the same or do they do different things? 
In addition to that, the function is not tested at all. 

Unit tests should be written and the `replicate_array` code verified.

CM: 18/9/23:
Reviewing the 2 functions identified here, being herbert_core/utilities/maths/replicate_array.m and horace_core/sqw/@sqw/private/replicate_array.m, the two functions do do the same thing. Their methodology is slightly different. The herbert one calculates a series of positions in an array large enough to hold the replicate, and then fills that array between these positions; while the horace one creates a set of sub-arrays, one for each replications, and then concatenates them. Both have the same special case that if the replication numbers argument is empty, an empty integers array (size 0,1) is created, which is not documented. Toby is original author of both.

TGP 09/02/24:
It turns out that at in R2015a, well after Horace was originally written, that Matlab introduced a function repelem that performs essentially the same operation. Cursory tests at the command line suggest that the only difference is in the shape of the output array: repelem preserves the shape of the input array, just expanded along dimensions, whereas replicate_array always produces a column vector. That is, 
          vout = replicate_array (v, n)
is equivalent to 
          vout = repelem (v(:), n(:))
Timing tests across a wide range of vector v lengths and average values of elements of n show that 
(1) The sqw/private method is between 2 and 8 times slower than the Herbert version
(2) repelem is between 20% slower and a factor of 25 times faster than the Herbert version

The correct solution will be either to simply wrap repelem to form replicate_array, replicate_iarray and replicate_logarray, possibly even substitute the calls throughout Horace and Herbert with calls to repelem.

**Comment by tgperring** [comment]
This issue was resolved in PR #1543
