### ISSUE TITLE
Setting single instrument or sample on Experiment resets unique objects container

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#906]
Is this still desirable behavior? If yes, -- fine, if not, it should be fixed
The example is in 
`test_experiment->test_experiment_methods:test_single_sample_sets_up_array`

**Comment by cmarooney-stfc** [comment]
The code works like this - if you take an experiment with existing runs defined and samples defined for them, and reset the samples to a single sample or container of samples, then IF the assigned value is a single sample or has the right number of samples for the number of runs in the experiment, the samples will take the new assigned values - if it is a single sample it will be replicated to the number of runs. Other numbers of samples will fail check_combo_args and will not be added. 

Test for this extended in PR.
