### ISSUE TITLE
Run Matlab tests in CI builds

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#91]
Currently, Matlab tests are not run in our CI builds.

To run the tests we will need to clone Herbert somewhere in the Jenkins workspace. We'll need to build Herbert's mex files as well unless we can grab the binaries from elsewhere?

We'll also need to resolve #86 so that Matlab can find the mex files that are compiled, and we can test against them.

Outcome:
- [x] MATLAB tests executed as part of HERBERT build on Jenkins
- [ ] MATLAB tests executed as part of HORACE build on Jenkins
- [ ] MATLAB tests can still be executed on Developer machine

**Comment by nickbattam-tessella** [comment]
Required for #30

**Comment by nickbattam-tessella** [comment]
Solution for Herbert (https://github.com/pace-neutrons/Herbert/issues/33) completed

**Comment by nickbattam-tessella** [comment]
Any failing MATLAB tests should be disabled as part of this this ticket; new issues must be created to fix them.
