### ISSUE TITLE
Refactor IX_mask and IX_map

### ISSUE THREAD

**Issue by tgperring** [pace-neutrons/Horace#922]
IX_mask and IX_map are currently of the old Matlab class definition. They need to be updated prior to the refactoring of the old mgenie detector tools in ticket #921.

This was raised earlier before Herbert was merged into Horace. The ticket (Herbert ticket 426) does not seem to have been transferred during the merge.

**Comment by cmarooney-stfc** [comment]
@tgperring Toby, can you prioritise this please

**Comment by tgperring** [comment]
Implemented in PR #1469 - closes issue.
