### ISSUE TITLE
Verify the spherical coordinate system meaning and description

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#954]
Physical verification of the meaning of the spherical coordinate system, if it is correctly oriented vrt. the instrument and the description corresponds to the actual formulas used. See `spher_proj` class description (rows 5-...)

The question to answer are:
1) is the suggested coordinate system convenient for users. (e.g. phi calculated with correct sign and from proper direction)
2) Is the description provided for the spheirclal projection correct and comprehensive
3) Do we neeed to allow change in the spherical coordinate system -- redirect spheciral axes along other coordinate axes (not beam direction)
4) Do we want to allow offset (not the centre of coordinate system)
5) do we need other units for Q (currently A^-1) only (mod(hkl) ? nonorthogonal, eliptic)

6) spherical cut from dnd is probably incorrect or should be tested. If there are any cut from dnd (not axes aligned), do we need spherical cut too?

**Comment by cmarooney-stfc** [comment]
@abuts to return to Christian Balz to arrange a face to face meeting to resolve this

**Comment by abuts** [comment]
fixed by Re #1638
